version: '3.8'

services:
  mysql-game-app:
    image: mysql:latest
    container_name: mysql-game-app
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senhasegura
      MYSQL_DATABASE: game
    ports:
      - "3307:3306"
    volumes:
      - mysql-game:/var/lib/mysql
    networks:
      - game-app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-game-app
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: senhasegura
    ports:
      - "8081:80"
    networks:
      - game-app-network

volumes:
  mysql-game:

networks:
  game-app-network:
    driver: bridge